# Generated by Django 5.0.4 on 2024-04-22 16:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("locker", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"verbose_name": "Món hàng", "verbose_name_plural": "Món hàng"},
        ),
    ]
