# Generated by Django 5.0.4 on 2024-04-22 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locker", "0002_alter_item_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="quantity",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Số lượng",
            ),
        ),
    ]
