# Generated by Django 5.0.4 on 2024-04-22 17:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("locker", "0005_alter_item_locker"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="locker",
            options={"verbose_name": "Tủ đồ", "verbose_name_plural": "Tủ đồ"},
        ),
    ]
