# Generated by Django 5.0.4 on 2024-04-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apartment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="status",
            field=models.CharField(
                choices=[
                    ("EMPTY", "Trống"),
                    ("INHABITED", "Có người ở"),
                    ("ABOUT_TO_MOVE", "Sắp chuyển đi"),
                ],
                default="EMPTY",
                max_length=20,
                verbose_name="Trạng thái",
            ),
        ),
    ]
