# Generated by Django 5.0.4 on 2024-04-17 16:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apartment", "0002_alter_apartmentbuilding_phone_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apartment",
            options={"verbose_name": "Căn hộ", "verbose_name_plural": "Căn hộ"},
        ),
        migrations.AlterModelOptions(
            name="apartmentbuilding",
            options={"verbose_name": "Chung cư", "verbose_name_plural": "Chung cư"},
        ),
        migrations.AlterModelOptions(
            name="apartmenttype",
            options={
                "verbose_name": "Loại căn hộ",
                "verbose_name_plural": "Loại căn hộ",
            },
        ),
        migrations.AlterModelOptions(
            name="building",
            options={"verbose_name": "Tòa nhà", "verbose_name_plural": "Tòa nhà"},
        ),
    ]
