version: '3.9'

services:
  mysql:
    image: mysql:latest
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    env_file:
      - ./.env.container
  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis:/data
    env_file:
      - ./.env.container
  api:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - mysql
      - redis
    env_file:
      - ./.env.container

volumes:
  mysql: {}
  redis: {}
