version: '3.9'

services:
  mysql:
    image: mysql:latest
    volumes:
      - mysql:/var/lib/mysql
    env_file:
      - ./.env.production
  api:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - mysql
    env_file:
      - ./.env.production

volumes:
  mysql: {}
