openapi: 3.0.3
info:
  title: OceanView API
  version: 1.0.0
paths:
  /users/{id}/active/:
    patch:
      operationId: users_active_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedActiveUser'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedActiveUser'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedActiveUser'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
  /users/current/:
    get:
      operationId: users_current_retrieve
      tags:
      - users
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
  /users/forgot-password/:
    post:
      operationId: users_forgot_password_create
      tags:
      - users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForgotPassword'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ForgotPassword'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ForgotPassword'
        required: true
      security:
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResetPasswordMethod'
          description: ''
  /users/login/:
    post:
      operationId: users_login_create
      tags:
      - users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Login'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Login'
        required: true
      security:
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogonUser'
          description: ''
  /users/reset-password/:
    get:
      operationId: users_reset_password_retrieve
      tags:
      - users
      security:
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: users_reset_password_create
      tags:
      - users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPassword'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ResetPassword'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ResetPassword'
        required: true
      security:
      - {}
      responses:
        '200':
          description: No response body
  /users/send-otp/:
    post:
      operationId: users_send_otp_create
      tags:
      - users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForgotPassword'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ForgotPassword'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ForgotPassword'
        required: true
      security:
      - {}
      responses:
        '200':
          description: No response body
  /users/send-reset-password-link/:
    post:
      operationId: users_send_reset_password_link_create
      tags:
      - users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForgotPassword'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ForgotPassword'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ForgotPassword'
        required: true
      security:
      - {}
      responses:
        '200':
          description: No response body
  /users/verify-otp/:
    post:
      operationId: users_verify_otp_create
      tags:
      - users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerifyOTP'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/VerifyOTP'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/VerifyOTP'
        required: true
      security:
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResetPassword'
          description: ''
components:
  schemas:
    ForgotPassword:
      type: object
      properties:
        resident_id:
          type: string
      required:
      - resident_id
    Login:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
          writeOnly: true
      required:
      - password
      - username
    LogonUser:
      type: object
      properties:
        resident_id:
          type: string
          title: Mã số cư dân
          maxLength: 6
          minLength: 6
        personal_information:
          $ref: '#/components/schemas/PersonalInformation'
        password:
          type: string
          title: Mật khẩu
          maxLength: 128
          minLength: 8
        avatar:
          type: string
          readOnly: true
        is_staff:
          type: boolean
          title: Là staff
        is_superuser:
          type: boolean
          title: Là superuser
        status:
          type: string
          readOnly: true
        issued_by:
          type: string
          title: Cấp phát bởi
          nullable: true
        token:
          $ref: '#/components/schemas/Token'
      required:
      - avatar
      - password
      - personal_information
      - resident_id
      - status
      - token
    PatchedActiveUser:
      type: object
      properties:
        avatar:
          type: string
          format: uri
        password:
          type: string
          writeOnly: true
    PersonalInformation:
      type: object
      properties:
        citizen_id:
          type: string
          title: Số căn cước công dân
          maxLength: 12
          minLength: 12
        full_name:
          type: string
          title: Họ tên
          maxLength: 50
        date_of_birth:
          type: string
          format: date
          nullable: true
          title: Ngày sinh
        phone_number:
          type: string
          title: Số điện thoại
          maxLength: 11
          minLength: 10
        email:
          type: string
          format: email
          nullable: true
          maxLength: 254
        hometown:
          type: string
          nullable: true
          title: Quê quán
          maxLength: 50
        gender:
          type: string
          readOnly: true
      required:
      - citizen_id
      - full_name
      - gender
      - phone_number
    ResetPassword:
      type: object
      properties:
        password:
          type: string
        confirm_password:
          type: string
      required:
      - confirm_password
      - password
    ResetPasswordMethod:
      type: object
      properties:
        methods:
          type: array
          items: {}
      required:
      - methods
    Token:
      type: object
      properties:
        access_token:
          type: string
        refresh_token:
          type: string
        token_type:
          type: string
        scope:
          type: string
      required:
      - access_token
      - refresh_token
      - scope
      - token_type
    TokenResetPassword:
      type: object
      properties:
        token:
          type: string
      required:
      - token
    User:
      type: object
      properties:
        resident_id:
          type: string
          title: Mã số cư dân
          maxLength: 6
          minLength: 6
        personal_information:
          $ref: '#/components/schemas/PersonalInformation'
        password:
          type: string
          writeOnly: true
          title: Mật khẩu
          maxLength: 128
          minLength: 8
        avatar:
          type: string
          readOnly: true
        is_staff:
          type: boolean
          title: Là staff
        is_superuser:
          type: boolean
          title: Là superuser
        status:
          type: string
          readOnly: true
        issued_by:
          type: string
          title: Cấp phát bởi
          nullable: true
      required:
      - avatar
      - password
      - personal_information
      - resident_id
      - status
    VerifyOTP:
      type: object
      properties:
        resident_id:
          type: string
        otp:
          type: string
      required:
      - otp
      - resident_id
  securitySchemes:
    oauth2:
      type: oauth2
      flows: {}
