# Generated by Django 5.0.4 on 2024-05-14 03:20

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_news_is_broadcast"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Nội dung"),
        ),
    ]
