# Generated by Django 5.0.4 on 2024-05-29 03:06

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_alter_news_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="is_banner",
            field=models.BooleanField(default=False, verbose_name="Banner"),
        ),
        migrations.AddField(
            model_name="news",
            name="thumbnail",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="Ảnh"
            ),
        ),
    ]
