# Generated by Django 5.0.4 on 2024-05-07 04:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guide",
            options={"verbose_name": "Cẩm nang", "verbose_name_plural": "Cẩm nang"},
        ),
        migrations.AlterModelOptions(
            name="guidecategory",
            options={
                "verbose_name": "Danh mục cẩm nang",
                "verbose_name_plural": "Danh mục cẩm nang",
            },
        ),
    ]
