# Generated by Django 5.0.4 on 2024-04-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fcmtoken",
            name="device_type",
            field=models.CharField(
                choices=[("WEB", "Web"), ("ANDROID", "Android")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fcmtoken",
            name="token",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
