# Generated by Django 5.0.4 on 2024-04-28 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0002_fcmtoken_device_type_alter_fcmtoken_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fcmtoken",
            name="device_type",
            field=models.CharField(
                choices=[("WEB", "Web"), ("ANDROID", "Android")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="fcmtoken",
            name="token",
            field=models.CharField(
                max_length=163,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(163)],
            ),
        ),
    ]
