# Generated by Django 5.0.4 on 2024-04-29 17:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0004_notificationcontent_remove_fcmtoken_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"verbose_name": "Thông báo", "verbose_name_plural": "Thông báo"},
        ),
        migrations.AlterModelOptions(
            name="notificationcontent",
            options={
                "verbose_name": "Nội dung thông báo",
                "verbose_name_plural": "Nội dung thông báo",
            },
        ),
        migrations.AlterModelOptions(
            name="notificationcreator",
            options={
                "verbose_name": "Người tạo thông báo",
                "verbose_name_plural": "Người tạo thông báo",
            },
        ),
    ]
