# Generated by Django 5.0.4 on 2024-05-08 16:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0011_alter_notificationcontent_entity_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationcontent",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="Ảnh"
            ),
        ),
    ]
