# Generated by Django 5.0.4 on 2024-05-08 16:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0012_notificationcontent_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationcontent",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default="https://res.cloudinary.com/diojasks1/image/upload/v1714901151/ff0shecjx5xmzojyg6oq.jpg",
                max_length=255,
                null=True,
                verbose_name="Ảnh",
            ),
        ),
    ]
