# Generated by Django 5.0.4 on 2024-05-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0013_alter_notificationcontent_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationcontent",
            name="image",
            field=models.CharField(
                blank=True,
                default="https://res.cloudinary.com/diojasks1/image/upload/v1714901151/ff0shecjx5xmzojyg6oq.jpg",
                max_length=200,
                null=True,
                verbose_name="Ảnh",
            ),
        ),
    ]
