# Generated by Django 5.0.4 on 2024-05-10 01:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0014_alter_notificationcontent_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationcontent",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("SERVICE_REGISTER", "Đăng ký dịch vụ"),
                    ("SERVICE_REISSUE", "Cấp lại"),
                    ("FEEDBACK_POST", "Đăng phản ánh"),
                    ("INVOICE_PROOF_IMAGE_PAYMENT", "Thanh toán"),
                    ("NEWS_POST", "Đăng thông báo"),
                    ("INVOICE_CREATE", "Nhận hóa đơn"),
                ],
                max_length=100,
                verbose_name="Loại thông báo",
            ),
        ),
        migrations.AlterField(
            model_name="notificationcontent",
            name="image",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Ảnh"
            ),
        ),
    ]
