# Generated by Django 5.0.4 on 2024-05-14 01:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0016_alter_notificationcontent_entity_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationcontent",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("SERVICE_REGISTER", "Đăng ký dịch vụ"),
                    ("SERVICE_APPROVED", "Đã duyệt đăng ký"),
                    ("SERVICE_REJECTED", "Đã từ chối đăng ký"),
                    ("REISSUE_APPROVED", "Đã duyệt cấp lại"),
                    ("REISSUE_REJECTED", "Đã từ chối cấp lại"),
                    ("SERVICE_REISSUE", "Cấp lại"),
                    ("FEEDBACK_POST", "Đăng phản ánh"),
                    ("INVOICE_PROOF_IMAGE_PAYMENT", "Thanh toán"),
                    ("NEWS_POST", "Đăng thông báo"),
                    ("INVOICE_CREATE", "Nhận hóa đơn"),
                    ("LOCKER_ITEM_ADD", "Đã nhận giúp"),
                ],
                max_length=100,
                verbose_name="Loại thông báo",
            ),
        ),
    ]
