# Generated by Django 5.0.4 on 2024-05-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0017_alter_notificationcontent_entity_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationcontent",
            name="entity_id",
            field=models.CharField(max_length=100, verbose_name="Mã thực thể"),
        ),
    ]
