# Generated by Django 5.0.4 on 2024-04-22 09:24

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Tiêu đề")),
                ("content", models.TextField(max_length=500, verbose_name="Nội dung")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("QUESTION", "Thắc mắc"),
                            ("COMPLAIN", "Phàn nàn"),
                            ("SUPPORT", "Hỗ trợ"),
                            ("OTHER", "Khác"),
                        ],
                        max_length=10,
                        verbose_name="Loại",
                    ),
                ),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="Ảnh"
                    ),
                ),
            ],
        ),
    ]
