# Generated by Django 5.0.4 on 2024-04-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="deleted",
            field=models.BooleanField(default=False, verbose_name="Đã xóa"),
        ),
    ]
