# Generated by Django 5.0.4 on 2024-05-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0002_alter_feedback_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="deleted",
            field=models.BooleanField(default=False, verbose_name="Đã bị xóa"),
        ),
    ]
