# Generated by Django 5.0.4 on 2024-05-09 03:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0003_alter_feedback_deleted"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatsFeedback",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("feedback.feedback",),
        ),
    ]
