# Generated by Django 5.0.4 on 2024-05-09 03:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0004_statsfeedback"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="statsfeedback",
            options={
                "verbose_name": "Thống kê phản ánh",
                "verbose_name_plural": "Thống kê phản ánh",
            },
        ),
    ]
