# Generated by Django 5.0.4 on 2024-06-08 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inbox",
            name="last_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inbox_last_message",
                to="chat.message",
                verbose_name="Tin nhắn cuối cùng",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="inbox",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="chat.inbox",
                verbose_name="Hộp thư đến",
            ),
        ),
    ]
