# Generated by Django 5.0.4 on 2024-04-22 16:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("apartment", "__first__"),
        ("user", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "service_id",
                    models.CharField(
                        choices=[
                            ("ACCESS_CARD", "Thẻ ra vào"),
                            ("RESIDENT_CARD", "Thẻ cư dân"),
                            ("BYCYCLE_PARKING_CARD", "Thẻ gửi xe đạp"),
                            ("MOTOR_PARKING_CARD", "Thẻ gửi xe máy"),
                            ("CAR_PARKING_CARD", "Thẻ gửi xe ô tô"),
                        ],
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Mã dịch vụ",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Tên dịch vụ")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=11,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Giá",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dịch vụ",
                "verbose_name_plural": "Dịch vụ",
            },
        ),
        migrations.CreateModel(
            name="Relative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "relationship",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Mối quan hệ"
                    ),
                ),
                (
                    "personal_information",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.personalinformation",
                        verbose_name="Thông tin cá nhân",
                    ),
                ),
                (
                    "residents",
                    models.ManyToManyField(
                        to=settings.AUTH_USER_MODEL, verbose_name="Danh sách cư dân"
                    ),
                ),
            ],
            options={
                "verbose_name": "Người thân",
                "verbose_name_plural": "Người thân",
            },
        ),
        migrations.CreateModel(
            name="ServiceRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAITING_FOR_APPROVAL", "Chờ được xét duyệt"),
                            ("APPROVED", "Đã được duyệt"),
                        ],
                        default="WAITING_FOR_APPROVAL",
                        max_length=30,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "personal_information",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.personalinformation",
                        verbose_name="Người sử dụng dịch vụ",
                    ),
                ),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cư dân đăng ký",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="service.service",
                        verbose_name="Dịch vụ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Đăng ký dịch vụ",
                "verbose_name_plural": "Đăng ký dịch vụ",
            },
        ),
        migrations.CreateModel(
            name="VehicleInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "license_plate",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(6)],
                        verbose_name="Biển số",
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("BYCYCLE", "Xe đạp"),
                            ("MOTORBIKE", "Xe máy"),
                            ("CAR", "Xe ô tô"),
                        ],
                        max_length=20,
                        verbose_name="Loại phương tiện",
                    ),
                ),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apartment.apartment",
                        verbose_name="Căn hộ",
                    ),
                ),
                (
                    "service_registration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="service.serviceregistration",
                        verbose_name="Dịch vụ đăng ký",
                    ),
                ),
            ],
            options={
                "verbose_name": "Thông tin phương tiện",
                "verbose_name_plural": "Thông tin phương tiện",
            },
        ),
    ]
