# Generated by Django 5.0.4 on 2024-04-08 14:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPermission',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('registered_person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.personalinformation', verbose_name='Người thân')),
                ('status', models.CharField(choices=[('W', 'Chờ được xét duyệt'), ('A', 'Đã được duyệt')], default='W', max_length=1, verbose_name='Trạng thái')),
                ('resident_registered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cư dân đăng ký')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReceiveParkingCardPermission',
            fields=[
                ('accesspermission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='service.accesspermission')),
                ('license_plate', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinValueValidator(6)], verbose_name='Biển số')),
                ('vehicle_type', models.CharField(choices=[('B', 'Xe đạp'), ('M', 'Xe máy'), ('C', 'Xe ô tô')], max_length=1, verbose_name='Loại phương tiện')),
                ('number_of_seats', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số chỗ ngồi')),
            ],
            options={
                'abstract': False,
            },
            bases=('service.accesspermission',),
        ),
    ]
