# Generated by Django 5.0.4 on 2024-05-10 04:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="price",
            field=models.PositiveBigIntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Giá",
            ),
        ),
    ]
