# Generated by Django 5.0.4 on 2024-04-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceregistration",
            name="status",
            field=models.CharField(
                choices=[
                    ("WAITING_FOR_APPROVAL", "Chờ được xét duyệt"),
                    ("APPROVED", "Đã được duyệt"),
                    ("CANCELED", "Đã hủy"),
                ],
                default="WAITING_FOR_APPROVAL",
                max_length=30,
                verbose_name="Trạng thái",
            ),
        ),
    ]
