# Generated by Django 5.0.4 on 2024-04-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="service_id",
            field=models.CharField(
                choices=[
                    ("ACCESS_CARD", "Thẻ ra vào"),
                    ("RESIDENT_CARD", "Thẻ cư dân"),
                    ("BYCYCLE_PARKING_CARD", "Thẻ gửi xe đạp"),
                    ("MOTOR_PARKING_CARD", "Thẻ gửi xe máy"),
                    ("CAR_PARKING_CARD", "Thẻ gửi xe ô tô"),
                ],
                max_length=30,
                primary_key=True,
                serialize=False,
                verbose_name="Mã dịch vụ",
            ),
        ),
        migrations.AlterField(
            model_name="serviceregistration",
            name="status",
            field=models.CharField(
                choices=[
                    ("WAITING_FOR_APPROVAL", "Chờ được xét duyệt"),
                    ("APPROVED", "Đã được duyệt"),
                ],
                default="WAITING_FOR_APPROVAL",
                max_length=30,
                verbose_name="Trạng thái",
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinformation",
            name="vehicle_type",
            field=models.CharField(
                choices=[
                    ("BYCYCLE", "Xe đạp"),
                    ("MOTORBIKE", "Xe máy"),
                    ("CAR", "Xe ô tô"),
                ],
                max_length=20,
                verbose_name="Loại phương tiện",
            ),
        ),
    ]
