# Generated by Django 5.0.4 on 2024-04-19 11:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="relative",
            name="resident",
        ),
        migrations.AddField(
            model_name="relative",
            name="residents",
            field=models.ManyToManyField(
                to=settings.AUTH_USER_MODEL, verbose_name="Danh sách cư dân"
            ),
        ),
    ]
