# Generated by Django 5.0.4 on 2024-05-13 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0002_alter_service_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceregistration",
            name="payment",
            field=models.CharField(
                choices=[
                    ("FREE", "Miễn phí"),
                    ("DAILY", "DAILY"),
                    ("MONTHLY", "Theo tháng"),
                    ("IMMEDIATELY", "Ngay lúc đăng ký"),
                ],
                default="MONTHLY",
                max_length=20,
                verbose_name="Hình thức thanh toán",
            ),
        ),
    ]
