# Generated by Django 5.0.4 on 2024-04-23 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0002_alter_serviceregistration_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicleinformation",
            name="service_registration",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicle_information",
                to="service.serviceregistration",
                verbose_name="Dịch vụ đăng ký",
            ),
        ),
    ]
