# Generated by Django 5.0.4 on 2024-04-23 08:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apartment", "0001_initial"),
        ("service", "0003_alter_vehicleinformation_service_registration"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="VehicleInformation",
            new_name="Vehicle",
        ),
        migrations.AlterModelOptions(
            name="vehicle",
            options={
                "verbose_name": "Phương tiện",
                "verbose_name_plural": "Phương tiện",
            },
        ),
    ]
