# Generated by Django 5.0.4 on 2024-04-23 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0004_rename_vehicleinformation_vehicle_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="service_registration",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="service.serviceregistration",
                verbose_name="Dịch vụ đăng ký",
            ),
        ),
    ]
