# Generated by Django 5.0.4 on 2024-04-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0005_alter_vehicle_service_registration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="service_id",
            field=models.CharField(
                choices=[
                    ("ACCESS_CARD", "Thẻ ra vào"),
                    ("RESIDENT_CARD", "Thẻ cư dân"),
                    ("BICYCLE_PARKING_CARD", "Thẻ gửi xe đạp"),
                    ("MOTOR_PARKING_CARD", "Thẻ gửi xe máy"),
                    ("CAR_PARKING_CARD", "Thẻ gửi xe ô tô"),
                ],
                max_length=30,
                primary_key=True,
                serialize=False,
                verbose_name="Mã dịch vụ",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="vehicle_type",
            field=models.CharField(
                choices=[
                    ("BICYCLE", "Xe đạp"),
                    ("MOTORBIKE", "Xe máy"),
                    ("CAR", "Xe ô tô"),
                ],
                max_length=20,
                verbose_name="Loại phương tiện",
            ),
        ),
    ]
