# Generated by Django 5.0.4 on 2024-05-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0005_alter_reissuecard_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reissuecard",
            name="previous_status",
            field=models.CharField(
                choices=[
                    ("WAITING_FOR_APPROVAL", "Chờ được xét duyệt"),
                    ("APPROVED", "Đã được duyệt"),
                    ("REJECTED", "Bị từ chối"),
                    ("CANCELED", "Đã hủy"),
                ],
                default=None,
                max_length=30,
                verbose_name="Trạng thái trước",
            ),
        ),
        migrations.AddField(
            model_name="serviceregistration",
            name="previous_status",
            field=models.CharField(
                choices=[
                    ("WAITING_FOR_APPROVAL", "Chờ được xét duyệt"),
                    ("APPROVED", "Đã được duyệt"),
                    ("REJECTED", "Bị từ chối"),
                    ("CANCELED", "Đã hủy"),
                ],
                default=None,
                max_length=30,
                verbose_name="Trạng thái trước",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="deleted",
            field=models.BooleanField(default=False, verbose_name="Đã bị xóa"),
        ),
    ]
