# Generated by Django 5.0.4 on 2024-04-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0006_alter_service_service_id_alter_vehicle_vehicle_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceregistration",
            name="status",
            field=models.CharField(
                choices=[
                    ("WAITING_FOR_APPROVAL", "Chờ được xét duyệt"),
                    ("APPROVED", "Đã được duyệt"),
                    ("REJECT", "Bị từ chối"),
                    ("CANCELED", "Đã hủy"),
                ],
                default="WAITING_FOR_APPROVAL",
                max_length=30,
                verbose_name="Trạng thái",
            ),
        ),
    ]
