# Generated by Django 5.0.4 on 2024-05-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0006_reissuecard_previous_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reissuecard",
            name="previous_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WAITING_FOR_APPROVAL", "Chờ được xét duyệt"),
                    ("APPROVED", "Đã được duyệt"),
                    ("REJECTED", "Bị từ chối"),
                    ("CANCELED", "Đã hủy"),
                ],
                default=None,
                max_length=30,
                null=True,
                verbose_name="Trạng thái trước",
            ),
        ),
        migrations.AlterField(
            model_name="serviceregistration",
            name="previous_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WAITING_FOR_APPROVAL", "Chờ được xét duyệt"),
                    ("APPROVED", "Đã được duyệt"),
                    ("REJECTED", "Bị từ chối"),
                    ("CANCELED", "Đã hủy"),
                ],
                default=None,
                max_length=30,
                null=True,
                verbose_name="Trạng thái trước",
            ),
        ),
    ]
