# Generated by Django 5.0.4 on 2024-05-02 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0007_alter_serviceregistration_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReissueCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAITING_FOR_APPROVAL", "Chờ được xét duyệt"),
                            ("APPROVED", "Đã được duyệt"),
                            ("REJECT", "Bị từ chối"),
                            ("CANCELED", "Đã hủy"),
                        ],
                        default=[
                            ("WAITING_FOR_APPROVAL", "Chờ được xét duyệt"),
                            ("APPROVED", "Đã được duyệt"),
                            ("REJECT", "Bị từ chối"),
                            ("CANCELED", "Đã hủy"),
                        ],
                        max_length=30,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "service_registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="service.serviceregistration",
                        verbose_name="Đăng ký dịch vụ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cấp  lại thẻ",
                "verbose_name_plural": "Cấp  lại thẻ",
            },
        ),
    ]
