# Generated by Django 5.0.4 on 2024-05-29 08:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0007_alter_reissuecard_previous_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="deleted",
        ),
    ]
