# Generated by Django 5.0.4 on 2024-05-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0009_alter_reissuecard_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="reissuecard",
            name="deleted",
            field=models.BooleanField(default=False, verbose_name="Đã bị xóa"),
        ),
        migrations.AddField(
            model_name="serviceregistration",
            name="deleted",
            field=models.BooleanField(default=False, verbose_name="Đã bị xóa"),
        ),
    ]
