# Generated by Django 5.0.4 on 2024-05-02 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apartment", "0001_initial"),
        ("service", "0010_reissuecard_deleted_serviceregistration_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceregistration",
            name="apartment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="apartment.apartment",
                verbose_name="Căn hộ",
            ),
        ),
    ]
