# Generated by Django 5.0.4 on 2024-05-02 14:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0011_serviceregistration_apartment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="apartment",
        ),
    ]
