# Generated by Django 5.0.4 on 2024-05-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="number_of_unread_notifications",
            new_name="unread_notifications",
        ),
        migrations.AddField(
            model_name="user",
            name="staff_unread_notifications",
            field=models.PositiveBigIntegerField(
                default=0, verbose_name="Thông báo chưa đọc admin"
            ),
        ),
    ]
