# Generated by Django 5.0.4 on 2024-04-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="locker_status",
            field=models.CharField(
                choices=[("EMPTY", "Trống"), ("NOT_EMPTY", "Có đồ")],
                default="EMPTY",
                max_length=10,
                verbose_name="Trạng thái tủ đồ",
            ),
        ),
    ]
