# Generated by Django 5.0.4 on 2024-04-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalinformation",
            name="gender",
            field=models.CharField(
                choices=[("MALE", "Nam"), ("FEMALE", "Nữ")],
                default="MALE",
                max_length=6,
                verbose_name="Giới tính",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="previous_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NOT_ISSUED_YET", "Chưa cấp phát"),
                    ("ISSUED", "Đã cấp phát"),
                    ("ACTIVE", "Đã kích hoạt"),
                    ("BANNED", "Bị khóa"),
                ],
                max_length=15,
                null=True,
                verbose_name="Trạng thái trước khị bị ban",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("NOT_ISSUED_YET", "Chưa cấp phát"),
                    ("ISSUED", "Đã cấp phát"),
                    ("ACTIVE", "Đã kích hoạt"),
                    ("BANNED", "Bị khóa"),
                ],
                default="NOT_ISSUED_YET",
                max_length=15,
                verbose_name="Trạng thái",
            ),
        ),
    ]
