# Generated by Django 5.0.4 on 2024-04-22 16:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_user_locker_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="locker_status",
        ),
    ]
