# Generated by Django 5.0.4 on 2024-04-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_personalinformation_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalinformation",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Ngày sinh"),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="hometown",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Quê quán"
            ),
        ),
    ]
