# Generated by Django 5.0.4 on 2024-04-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_user_number_of_unread_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="number_of_unread_notification",
            field=models.PositiveBigIntegerField(
                default=0, verbose_name="Thông báo chưa đọc"
            ),
        ),
    ]
