# Generated by Django 5.0.4 on 2024-04-30 05:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_alter_user_number_of_unread_notification"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="number_of_unread_notification",
            new_name="number_of_unread_notifications",
        ),
    ]
