# Generated by Django 5.0.4 on 2024-05-04 14:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="onlinewallet",
            options={
                "verbose_name": "Thanh toán qua ví điện tử",
                "verbose_name_plural": "Thanh toán qua ví điện tử",
            },
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={"verbose_name": "Thanh toán", "verbose_name_plural": "Thanh toán"},
        ),
        migrations.AlterModelOptions(
            name="proofimage",
            options={
                "verbose_name": "Ảnh chứng minh",
                "verbose_name_plural": "Ảnh chứng minh",
            },
        ),
    ]
