# Generated by Django 5.0.4 on 2024-04-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoicedetail",
            name="payment_method",
            field=models.CharField(
                choices=[("E_WALLET", "Ví điện tử"), ("PROOF_IMAGE", "Ủy nhiệm chi")],
                max_length=15,
                verbose_name="Phương thức thanh toán",
            ),
        ),
    ]
