# Generated by Django 5.0.4 on 2024-05-05 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0002_alter_onlinewallet_options_alter_payment_options_and_more"),
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoicedetail",
            name="service",
        ),
        migrations.AddField(
            model_name="invoicedetail",
            name="service_registration",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="service.serviceregistration",
                verbose_name="Đăng ký dịch vụ",
            ),
            preserve_default=False,
        ),
    ]
