# Generated by Django 5.0.4 on 2024-05-05 06:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0003_remove_invoicedetail_service_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=11,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Số tiền",
            ),
        ),
    ]
