# Generated by Django 5.0.4 on 2024-05-05 08:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0004_alter_invoice_total_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicedetail",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=11,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Số tiền",
            ),
            preserve_default=False,
        ),
    ]
