# Generated by Django 5.0.4 on 2024-05-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0005_invoicedetail_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Chờ thanh toán"),
                    ("PAID", "Đã thanh toán"),
                    ("OVERDUE", "Quá hạn"),
                ],
                default="PENDING",
                max_length=10,
                verbose_name="Trạng thái thanh toán",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUCCESS", "Thành công"),
                    ("CONFIRMING", "Đang xác nhận"),
                    ("INVALID", "Không hợp lệ"),
                ],
                default="CONFIRMING",
                max_length=20,
                verbose_name="Trạng thái",
            ),
        ),
    ]
