# Generated by Django 5.0.4 on 2024-05-05 09:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0006_invoice_status_alter_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proofimage",
            name="image",
            field=cloudinary.models.CloudinaryField(
                default="https://res.cloudinary.com/diojasks1/image/upload/v1713710625/jvwdbfxb84j7pkaci3nd.jpg",
                max_length=255,
                verbose_name="Ảnh chứng từ thanh toán",
            ),
            preserve_default=False,
        ),
    ]
