# Generated by Django 5.0.4 on 2024-05-08 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0007_alter_proofimage_image"),
        ("vnpay", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="onlinewallet",
            name="vnpay_billing",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="vnpay.billing",
                verbose_name="Thanh toán vnpay",
            ),
        ),
    ]
