# Generated by Django 5.0.4 on 2024-05-08 02:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0008_onlinewallet_vnpay_billing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="onlinewallet",
            name="transaction_code",
        ),
    ]
