# Generated by Django 5.0.4 on 2024-05-10 03:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0013_delete_invoicecreator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="onlinewallet",
            name="vnpay_billing",
        ),
        migrations.AddField(
            model_name="onlinewallet",
            name="reference_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Mã tham chiếu"
            ),
        ),
        migrations.AddField(
            model_name="onlinewallet",
            name="transaction_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Mã giao dịch"
            ),
        ),
        migrations.AddField(
            model_name="onlinewallet",
            name="wallet_type",
            field=models.CharField(
                choices=[("VNPAY", "VnPay"), ("MOMO", "Momo")],
                default="VNPAY",
                max_length=10,
                verbose_name="Loại ví",
            ),
            preserve_default=False,
        ),
    ]
