# Generated by Django 5.0.4 on 2024-05-10 04:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0014_remove_onlinewallet_vnpay_billing_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="total_amount",
            field=models.PositiveBigIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Số tiền",
            ),
        ),
        migrations.AlterField(
            model_name="invoicedetail",
            name="amount",
            field=models.PositiveBigIntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Số tiền",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="total_amount",
            field=models.PositiveBigIntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Số tiền",
            ),
        ),
    ]
