# Generated by Django 5.0.4 on 2024-05-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0016_alter_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Chờ thanh toán"),
                    ("PAID", "Đã thanh toán"),
                    ("OVERDUE", "Quá hạn"),
                    ("WAITING_FOR_APPROVAL", "Chờ phê duyệt"),
                ],
                default="PENDING",
                max_length=30,
                verbose_name="Trạng thái thanh toán",
            ),
        ),
    ]
