# Generated by Django 5.0.4 on 2024-05-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0017_alter_invoice_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="proofimage",
            name="status",
            field=models.CharField(
                choices=[
                    ("WAITING_FOR_APPROVAL", "Chờ được xét duyệt"),
                    ("APPROVED", "Đã được duyệt"),
                    ("REJECTED", "Bị từ chối"),
                ],
                default="WAITING_FOR_APPROVAL",
                max_length=30,
                verbose_name="Trạng thái",
            ),
        ),
    ]
